//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Food_Web.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MENU_ABOUT {
            get {
                return ResourceManager.GetString("MENU_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string MENU_BLOG {
            get {
                return ResourceManager.GetString("MENU_BLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact.
        /// </summary>
        public static string MENU_CONTACT {
            get {
                return ResourceManager.GetString("MENU_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string MENU_GALLEY {
            get {
                return ResourceManager.GetString("MENU_GALLEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MENU_HOME {
            get {
                return ResourceManager.GetString("MENU_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MENU_MENU {
            get {
                return ResourceManager.GetString("MENU_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Deals.
        /// </summary>
        public static string RS__Deals {
            get {
                return ResourceManager.GetString("RS_ Deals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive Deals.
        /// </summary>
        public static string RS__Exclusive {
            get {
                return ResourceManager.GetString("RS_ Exclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string RS__Pages {
            get {
                return ResourceManager.GetString("RS_ Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        public static string RS_Categories {
            get {
                return ResourceManager.GetString("RS_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products available.
        /// </summary>
        public static string RS_HC {
            get {
                return ResourceManager.GetString("RS_HC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Arrivals.
        /// </summary>
        public static string RS_New {
            get {
                return ResourceManager.GetString("RS_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Sale.
        /// </summary>
        public static string RS_Sale {
            get {
                return ResourceManager.GetString("RS_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search everything.
        /// </summary>
        public static string RS_seach {
            get {
                return ResourceManager.GetString("RS_seach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string RS_Store {
            get {
                return ResourceManager.GetString("RS_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Our ENGLISH Restaurant.
        /// </summary>
        public static string TITLE_WELCOME {
            get {
                return ResourceManager.GetString("TITLE_WELCOME", resourceCulture);
            }
        }
    }
}
